/**
 * Phase G: per-repo project agents — discover, plan, emit (max 3).
 * Canonical source: .omakaseagent/project-agents/*.md
 */

const fs = require('fs');
const path = require('path');

const MAX_PROJECT_AGENTS = 3;
const PROJECT_AGENTS_MARKER = '<!-- omakase-learn:project-agents -->';

const HARNESS_AGENT_DIRS = {
  cursor: '.cursor/agents',
  claude: '.claude/agents',
  agents: '.opencode/agents',
  grok: '.grok/agents',
  codex: '.codex/agents',
};

function readSafe(filePath) {
  try {
    return fs.readFileSync(filePath, 'utf8');
  } catch {
    return null;
  }
}

function slugify(s) {
  return s
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, '-')
    .replace(/^-|-$/g, '');
}

function parseFrontmatter(raw) {
  const m = raw.match(/^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/);
  if (!m) return { meta: {}, body: raw };
  const meta = {};
  for (const line of m[1].split('\n')) {
    const idx = line.indexOf(':');
    if (idx === -1) continue;
    meta[line.slice(0, idx).trim()] = line.slice(idx + 1).trim().replace(/^["']|["']$/g, '');
  }
  return { meta, body: m[2] };
}

function detectInstalledHarnesses(cwd) {
  return Object.entries(HARNESS_AGENT_DIRS)
    .filter(([_, dir]) => fs.existsSync(path.join(cwd, dir.split('/')[0])))
    .map(([name]) => name);
}

function discoverProjectAgentCandidates(cwd, pkg, stack) {
  const pkgSlug = slugify(pkg.name || path.basename(cwd));
  const proposals = [];

  if (stack.includes('Omakase skill source') || fs.existsSync(path.join(cwd, 'skill', 'SKILL.md'))) {
    proposals.push({
      slug: 'skill-maintainer',
      filename: 'skill-maintainer.md',
      name: `omakase-${pkgSlug}-skill`,
      description: `Maintains ${pkg.name} skill/, personas, and reference docs for this repo.`,
      body: `# Project agent: skill maintainer

Repo-specific extension for **${pkg.name}** skill source.

## Mandate
- Changes under \`skill/\` follow factory Class 2+ loop (brief, scenarios, gate).
- Authoring bar: \`reference/write-skills.md\`; audits: \`reference/skill-judge.md\` via @omakase-critic → skill-judge.
- Run \`npm run build\` after persona edits; \`npm run verify:native-agents\` + \`npm run verify:scenario-evals\`.
- Delegate structural review to @omakase-critic when risk is high.

## Memory
Read \`.omakaseagent/factory.md\`, \`taste.md\`, \`decisions.md\` before non-trivial edits.
`,
    });
  }

  if (fs.existsSync(path.join(cwd, 'bin')) || stack.includes('omakase CLI')) {
    proposals.push({
      slug: 'cli-maintainer',
      filename: 'cli-maintainer.md',
      name: `omakase-${pkgSlug}-cli`,
      description: `Maintains ${pkg.name} CLI (bin/, scripts/) and install smoke paths.`,
      body: `# Project agent: CLI maintainer

Repo-specific extension for **${pkg.name}** CLI and scripts.

## Mandate
- \`bin/\` and non-verify \`scripts/\` changes are Class 2 — gate + mechanical checks.
- Prefer extending existing commands; document flags in \`omakase help\`.
- Run relevant \`npm run verify:*\` before checkpoint.

## Memory
Read \`.omakaseagent/factory.md\` mechanical evidence list before claiming done.
`,
    });
  }

  const domainDirs = ['api', 'server', 'web', 'app', 'frontend', 'mobile', 'services'];
  for (const dir of domainDirs) {
    if (fs.existsSync(path.join(cwd, dir))) {
      proposals.push({
        slug: `${dir}-lead`,
        filename: `${dir}-lead.md`,
        name: `omakase-${pkgSlug}-${dir}`,
        description: `Domain lead for ${pkg.name} \`${dir}/\` — stack-specific implementation.`,
        body: `# Project agent: ${dir} domain lead

Repo-specific extension for **${pkg.name}** \`${dir}/\` work.

## Mandate
- Stay within \`${dir}/\` boundaries unless Engineer expands scope.
- Follow \`reference/task-intake.md\` and repo \`factory.md\` checks.
- Propose durable taste/decisions updates via @omakase-archivist when patterns emerge.

## Memory
Cite active \`taste.md\` bullets in every non-trivial deliverable.
`,
      });
      break;
    }
  }

  return proposals.slice(0, MAX_PROJECT_AGENTS);
}

function buildProjectAgentFile(candidate) {
  return `---
name: ${candidate.name}
description: "${candidate.description.replace(/"/g, '\\"')}"
model: inherit
project: true
---

${candidate.body.trim()}
`;
}

function buildNativeEmitContent(agentName, projectFileRel, description) {
  return `---
name: ${agentName}
description: "${description.replace(/"/g, '\\"')}"
model: inherit
---

# Omakase project agent

Canonical source: \`${projectFileRel}\` (regenerated by \`omakase learn\`).

{file:${projectFileRel}}
`;
}

function listExistingProjectAgents(projectDir) {
  if (!fs.existsSync(projectDir)) return [];
  return fs
    .readdirSync(projectDir)
    .filter((f) => f.endsWith('.md') && f !== 'README.md')
    .map((f) => path.join(projectDir, f));
}

function planProjectAgents(cwd, pkg, stack, options = {}) {
  const memDir = path.join(cwd, '.omakaseagent');
  const projectDir = path.join(memDir, 'project-agents');
  const files = [];
  const emitPlan = [];

  const readmePath = path.join(projectDir, 'README.md');
  if (!fs.existsSync(readmePath)) {
    files.push({
      path: readmePath,
      content: `# project-agents

Canonical **per-repo** agent bodies (max ${MAX_PROJECT_AGENTS}). Emitted to harness \`agents/\` on \`omakase learn\`.

Edit these files, then re-run \`omakase learn\` (or \`--project-agents-only\`) to refresh native stubs.

Namespaced ids: \`omakase-<package>-<role>\`. Core leads (@omakase-engineer, etc.) come from the package — never replace them here.
`,
    });
  }

  const candidates = discoverProjectAgentCandidates(cwd, pkg, stack);
  for (const c of candidates) {
    const target = path.join(projectDir, c.filename);
    if (!fs.existsSync(target)) {
      files.push({ path: target, content: buildProjectAgentFile(c) });
    }
  }

  const harnesses = detectInstalledHarnesses(cwd);
  const sourcesByBase = new Map();
  for (const src of listExistingProjectAgents(projectDir)) {
    sourcesByBase.set(path.basename(src), src);
  }
  for (const f of files) {
    if (f.path.includes('project-agents') && f.path.endsWith('.md') && !f.path.endsWith('README.md')) {
      sourcesByBase.set(path.basename(f.path), f.path);
    }
  }

  for (const src of sourcesByBase.values()) {
    const raw = readSafe(src) || files.find((f) => f.path === src)?.content;
    if (!raw) continue;
    const { meta } = parseFrontmatter(raw);
    const agentName = meta.name;
    const description = meta.description || 'Omakase project agent';
    if (!agentName) continue;
    const relFromRepo = path.relative(cwd, src).replace(/\\/g, '/');
    for (const harness of harnesses) {
      const agentDir = path.join(cwd, HARNESS_AGENT_DIRS[harness]);
      emitPlan.push({
        harness,
        path: path.join(agentDir, `${agentName}.md`),
        content: buildNativeEmitContent(agentName, relFromRepo, description),
        agentName,
      });
    }
  }

  const allSlugs = [
    ...new Set([
      ...candidates.map((c) => c.slug),
      ...[...sourcesByBase.keys()].map((f) => f.replace('.md', '')),
    ]),
  ].slice(0, MAX_PROJECT_AGENTS);

  return { files, emitPlan, candidates: allSlugs, harnesses };
}

function applyProjectAgentEmit(emitPlan, options = {}) {
  const written = [];
  for (const item of emitPlan) {
    if (options.dryRun) {
      written.push(path.relative(process.cwd(), item.path));
      continue;
    }
    fs.mkdirSync(path.dirname(item.path), { recursive: true });
    fs.writeFileSync(item.path, item.content, 'utf8');
    written.push(path.relative(process.cwd(), item.path));
  }
  return written;
}

function buildAgentsProjectSection(slugs) {
  if (!slugs.length) return '';
  const lines = slugs.map((s) => `- \`.omakaseagent/project-agents/${s}.md\` → emitted on learn`);
  return `

${PROJECT_AGENTS_MARKER}

**Project agents** (≤${MAX_PROJECT_AGENTS}, repo-specific):

${lines.join('\n')}
`;
}

module.exports = {
  MAX_PROJECT_AGENTS,
  PROJECT_AGENTS_MARKER,
  discoverProjectAgentCandidates,
  planProjectAgents,
  applyProjectAgentEmit,
  buildAgentsProjectSection,
  detectInstalledHarnesses,
};
